// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vivaply.API.Data;

#nullable disable

namespace Vivaply.API.Migrations
{
    [DbContext(typeof(VivaplyDbContext))]
    partial class VivaplyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.Igdb.GameMetadata", b =>
                {
                    b.Property<int>("IgdbId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DevelopersJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("GenresJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("double precision");

                    b.HasKey("IgdbId");

                    b.ToTable("GameMetadata");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.Igdb.UserGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IgdbId")
                        .HasColumnType("integer");

                    b.Property<string>("Review")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPlatform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("UserPlaytime")
                        .HasColumnType("double precision");

                    b.Property<double?>("UserRating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IgdbId");

                    b.HasIndex("UserId", "IgdbId")
                        .IsUnique();

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.Tmdb.MovieMetadata", b =>
                {
                    b.Property<int>("TmdbMovieId")
                        .HasColumnType("integer");

                    b.Property<string>("GenresJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("double precision");

                    b.HasKey("TmdbMovieId");

                    b.ToTable("MovieMetadata");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.Tmdb.ShowMetadata", b =>
                {
                    b.Property<int>("TmdbShowId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstAirDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenresJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastEpisodeAirDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastKnownEpisode")
                        .HasColumnType("integer");

                    b.Property<int?>("LastKnownSeason")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("NextEpisodeAirDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("double precision");

                    b.HasKey("TmdbShowId");

                    b.ToTable("ShowMetadata");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.UserMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Review")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TmdbMovieId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("UserRating")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TmdbMovieId");

                    b.HasIndex("UserId", "TmdbMovieId")
                        .IsUnique();

                    b.ToTable("UserMovies");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.UserShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastWatchedEpisode")
                        .HasColumnType("integer");

                    b.Property<int?>("LastWatchedSeason")
                        .HasColumnType("integer");

                    b.Property<string>("Review")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TmdbShowId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("UserRating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TmdbShowId");

                    b.HasIndex("UserId", "TmdbShowId")
                        .IsUnique();

                    b.ToTable("UserShows");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.WatchedEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Review")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("UserRating")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserShowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserShowId");

                    b.ToTable("WatchedEpisodes");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Finance.Wallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LockedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Gamification.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("bigint");

                    b.Property<int>("Intellect")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastStreakUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "SortOrder");

                    b.ToTable("PostAttachments");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostBookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostBookmarks");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostStats", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookmarkCount")
                        .HasColumnType("integer");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<int>("QuoteCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.ToTable("PostStats");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("AggregationWindowEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentEntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AggregateKey");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("SourceEntityType", "SourceEntityId");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId");

                    b.HasIndex("FollowingId");

                    b.HasIndex("FollowerId", "FollowingId")
                        .IsUnique();

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentPostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuotedPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextContent")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.HasIndex("ParentPostId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("QuotedPostId");

                    b.HasIndex("UserId", "PublishedAt");

                    b.ToTable("UserPosts");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityVisibility")
                        .HasColumnType("integer");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<int>("FollowPolicy")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileVisibility")
                        .HasColumnType("integer");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Knowledge.BookMetadata", b =>
                {
                    b.Property<string>("GoogleBookId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AuthorsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("double precision");

                    b.HasKey("GoogleBookId");

                    b.ToTable("BookMetadata");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Knowledge.UserBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleBookId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Review")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("UserRating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GoogleBookId");

                    b.HasIndex("UserId", "GoogleBookId")
                        .IsUnique();

                    b.ToTable("UserBooks");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Ratings.ContentRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId");

                    b.HasIndex("UserId", "SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("ContentRatings");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Ratings.ContentRatingStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("ContentRatingStats");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Statistics.ContentEngagementStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveCount")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<double>("CompletionRate")
                        .HasColumnType("double precision");

                    b.Property<int>("DroppedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastAggregatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListCount")
                        .HasColumnType("integer");

                    b.Property<int>("OnHoldCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlannedCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("ContentEngagementStats");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.Igdb.UserGame", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Entertainment.Igdb.GameMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("IgdbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.UserMovie", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Entertainment.Tmdb.MovieMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("TmdbMovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.UserShow", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Entertainment.Tmdb.ShowMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("TmdbShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.WatchedEpisode", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Entertainment.UserShow", "UserShow")
                        .WithMany("WatchedEpisodes")
                        .HasForeignKey("UserShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserShow");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Finance.Wallet", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Vivaply.API.Entities.Finance.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Gamification.UserProfile", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Vivaply.API.Entities.Gamification.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostAttachment", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.UserPost", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostBookmark", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.UserPost", "Post")
                        .WithMany("Bookmarks")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostLike", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.UserPost", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.PostStats", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.UserPost", "Post")
                        .WithOne("Stats")
                        .HasForeignKey("Vivaply.API.Entities.Identity.PostStats", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserActivity", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserFollow", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivaply.API.Entities.Identity.User", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserPost", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.UserActivity", "Activity")
                        .WithOne("Post")
                        .HasForeignKey("Vivaply.API.Entities.Identity.UserPost", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Vivaply.API.Entities.Identity.UserPost", "ParentPost")
                        .WithMany("Replies")
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vivaply.API.Entities.Identity.UserPost", "QuotedPost")
                        .WithMany("Quotes")
                        .HasForeignKey("QuotedPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("ParentPost");

                    b.Navigation("QuotedPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserPreferences", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Vivaply.API.Entities.Identity.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserRefreshToken", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Knowledge.UserBook", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Knowledge.BookMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("GoogleBookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Ratings.ContentRating", b =>
                {
                    b.HasOne("Vivaply.API.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Entertainment.UserShow", b =>
                {
                    b.Navigation("WatchedEpisodes");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.User", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Preferences");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserActivity", b =>
                {
                    b.Navigation("Post");
                });

            modelBuilder.Entity("Vivaply.API.Entities.Identity.UserPost", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Bookmarks");

                    b.Navigation("Likes");

                    b.Navigation("Quotes");

                    b.Navigation("Replies");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
